9856 dvui dev guide
konfuzio-ai/konfuzio-sdk pull request #186
Opened 2022-12-12 12:33 UTC by vebarina

2022-12-14 23:15 UTC, mexicat requested changes
Good job!

2022-12-14 23:15 UTC, mexicat commented on docs/dvui/guides.md
> +In the html we should load the script we created with the webpack and customise the variables we want. Please note that customising the variables is optional and that, as previously mentioned, any va
Capitalize "HTML". "The webpack" -> "webpack".

2022-12-14 23:15 UTC, mexicat commented on docs/dvui/guides.md
> +The following example includes the custom variables (Document id, Category id, User Token, Locale), but it is not necessary to add these.
Capitalize "ID". "Necessary" -> "mandatory".

2022-12-14 23:15 UTC, mexicat commented on docs/dvui/guides.md
> +In [this link](https://www.ais.com/using-a-vue-component-in-an-angular-app/) you will see a step by step on how to use the Document Validation UI in an Angular application.
"In this link" -> "at this link".

2022-12-14 23:15 UTC, mexicat commented on docs/dvui/guides.md
> +You can mark your Documents as public. Marking Documents as public will generate a read-only, publicly accessible view that does not require authentication. This allows you to share a link to the Doc
Mmm, maybe "publicly accessible URL" instead of "publicly accessible view" is clearer.

2022-12-14 23:15 UTC, mexicat commented on docs/dvui/index.md
> +This component is responsible for drawing the Document and handling any interaction with it. The main thing is that it uses [Konva JS](https://konvajs.org/docs/vue/index.html) to render a canvas elem
"The main thing is that it uses" -> "it uses".

2022-12-14 23:15 UTC, mexicat commented on docs/dvui/modes.md
> +This is the default mode of the app. In this mode, you will have a sample Document with annotations that you can only preview. The default API endpoint will be https://app.konfuzio.com and no user ac
"Unless configured, it uses the default API endpoint at https://app.konfuzio.com..."

2022-12-14 23:15 UTC, mexicat commented on docs/dvui/modes.md
> +If you want to run the widget in full mode to be able to interact with the Document by editing Annotations, Document pages and other functionalities, you will need to have a user account created (mor
* "you should generate a user Token, by accessing" -> remove the comma
* "more information in our “Managing users” section" -> can we link it?
* "If the account exists" -> "If the provided credentials are correct"
* "a Token will be generated that you can copy **and add to the env settings**" (maybe with a "see below"?)

2022-12-14 23:15 UTC, mexicat commented on docs/dvui/modes.md
> +You can create an environment variables file `.env` on the root of the repository based on the [`.env.example`](https://github.com/konfuzio-ai/konfuzio-capture-vue/blob/main/.env.example) for specify
"You can create" -> I would make it more "you have to create" or maybe something more indirect like "To complete the setup, create an env file..."

Then I think you can only list (maybe as a bullet list) the env options that are actually required and leave the rest in the documentation link (the env example is fine, but don't we have some markdown documentation for that?)

2022-12-15 10:49 UTC, vebarina commented on docs/dvui/modes.md
> +You can create an environment variables file `.env` on the root of the repository based on the [`.env.example`](https://github.com/konfuzio-ai/konfuzio-capture-vue/blob/main/.env.example) for specify
@mexicat I made the changes, but not sure what you refer to with the "markdown documentation" for the .env. As far as I know we just have the example file, but might be confused as to what you are talking about.

2022-12-19 08:12 UTC, mexicat commented on docs/dvui/modes.md
> +You can create an environment variables file `.env` on the root of the repository based on the [`.env.example`](https://github.com/konfuzio-ai/konfuzio-capture-vue/blob/main/.env.example) for specify
I was just talking about general documentation about the setting variables in the guides. If they're only in the `.env` example file it's OK like this.

2022-12-19 10:02 UTC, mexicat approved these changes

2022-12-19 10:03 UTC, merged